language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.3.3
  - 7.0
  - hhvm
 
matrix:
    include:
        - php: 5.3.3
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    allow_failures:
        - php: 7.0
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer.phar
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - mkdir -p build/logs
  - php -n php-cs-fixer.phar fix src -v --dry-run --level=symfony
  - php vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=build/config/phpcs.xml --ignore=*.html.php,*.config.php,*.twig.php src
  - php vendor/bin/phpmd src xml build/config/phpmd.xml --reportfile build/logs/pmd.xml
  - cp ~/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - php vendor/bin/phpunit -c travis.phpunit.xml
  - rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

after_script:
  - curl -s https://gist.github.com/satooshi/4750401/raw > travis/ColorCLI.php
  - curl -s https://gist.github.com/satooshi/4752226/raw > travis/junit.php
  - curl -s https://gist.github.com/satooshi/4958593/raw > travis/pmd.php
  - curl -s https://gist.github.com/satooshi/4958909/raw > travis/checkstyle.php
  - php travis/checkstyle.php
  - php travis/pmd.php
  - php travis/junit.php
  - php composer/bin/coveralls -v --exclude-no-stmt

